// Track list for Tabata Player
const tracks = [
    "LEA - Wohin Willst Du (Kuba Hardtechno Music)_tabata.mp3",
    "2 Fabiola - Lift U Up (1)_tabata.mp3", 
    "ABCDEFU (Age Pee Remix)_tabata.mp3", 
    "Alice - Per Elisa_tabata.mp3", 
    "Alice - Una Notte Speciale_tabata.mp3", 
    "Alles wird gut_tabata.mp3", 
    "Better When Youre Gone_tabata.mp3", 
    "CHARLY LOWNOISE & RE-STYLE feat. RICARDO MORENO - City Streets (Extended Mix)_tabata.mp3", 
    "Chris Brown - Yeah 3x (HBz Bounce Remix)_tabata.mp3", 
    "Danza Kuduro (Norda, Master Blaster, EmJo Remix Radio Edit)_tabata.mp3", 
    "Das geht ab - Wir feiern die ganze Nacht - Remix_tabata.mp3", 
    "Die Atzen, Norda & Master Blaster feat. DJ EmJo & DJ Basti - Das geht ab Remix (Official Visualizer)_tabata.mp3", 
    "Die Flippers - Wir sagen Danke schön [40 Jahre] (HBz u0026 Raphael Maier Remix)_tabata.mp3", 
    "Durch den Monsun_tabata.mp3", 
    "Froh & Munter_tabata.mp3", 
    "GAYLE - abcdefu (HBz u0026 Raphael Maier Remix)_tabata.mp3", 
    "GOETHE - HARRIS u0026 FORD EDIT - 2 ENGEL u0026 CHARLIE_tabata.mp3", 
    "Haddaway_tabata.mp3", 
    "Halo_tabata.mp3", 
    "Harris u0026 Ford - Survivors_tabata.mp3", 
    "Harris u0026 Ford - Turn Back Time  (Official Video)_tabata.mp3", 
    "Harris u0026 Ford feat. Addnfahrer - Hard, Style u0026 Volksmusik_tabata.mp3", 
    "HARRIS u0026 FORD feat. FiNCH - Freitag Samstag (Official Video HD)_tabata.mp3", 
    "Harris u0026 Ford x 2 Engel u0026 Charlie - Amsterdam (Official Video)_tabata.mp3", 
    "Harris u0026 Ford x DJ Gollum - Numb_tabata.mp3", 
    "Harris u0026 Ford x Faustix - Hollywood (feat. PollyAnna) [Official Audio]_tabata.mp3", 
    "HARRIS u0026 FORD x FiNCH - MAKE THE WORLD RAVE AGAIN_tabata.mp3", 
    "HARRiS u0026 FORD x FiNCH - NACHBARN_tabata.mp3", 
    "Harris u0026 Ford x ItaloBrothers - Weekend Party (Official Lyrics Video)_tabata.mp3", 
    "Harris u0026 Ford x Jebroer - Mutter (Official Video HD)_tabata.mp3", 
    "Harris u0026 Ford x Maxim Schunk - Lost in You (Official Video)_tabata.mp3", 
    "Harris u0026 Ford x Outsiders - Irrenhaus (Official Video 4K)_tabata.mp3", 
    "Harris u0026 Ford x Sound Rush - Died In Your Arms (Reloaded)_tabata.mp3", 
    "Harris u0026 Ford x Xillions - Won't Forget (Official Lyrics Video)_tabata.mp3", 
    "HBz - Gästeliste +1 (Official Video 4K)_tabata.mp3", 
    "HBz - King Kong (Official Video)_tabata.mp3", 
    "HBz x THOVI - WIR MACHEN RUM_tabata.mp3", 
    "Julian Sommer - Dicht im Flieger (Harris u0026 Ford Remix)_tabata.mp3", 
    "Kerstin Ott - Megamix_tabata.mp3", 
    "Looking for Freedom_tabata.mp3", 
    "Masterboy - Megamix_tabata.mp3", 
    "Nathan Evans - Drunken Sailor (Harris u0026 Ford Remix)_tabata.mp3", 
    "Oimara - Wackelkontakt (Darrix Hardstyle Remix)_tabata.mp3", 
    "Ok Without You_tabata.mp3", 
    "Olivia (Harris & Ford Remix) - Die Zipfelbuben_tabata.mp3", 
    "Olivia (Harris u0026 Ford Remix) - Die Zipfelbuben_tabata.mp3", 
    "Roland Kaiser - Dich zu lieben_tabata.mp3", 
    "Salsa Tequila (Damn-R Remix)_tabata.mp3", 
    "Scooter x Harris u0026 Ford – God Save The Rave (Official Video HD)_tabata.mp3", 
    "SDP x 257ers - Scheiße baut sich nicht von alleine (HBz Remix)  Videoclip_tabata.mp3", 
    "Spacekid - Moi... Lolita_tabata.mp3", 
    "Technotronic - Megamix_tabata.mp3", 
    "Tream - 3er BMW (Harris u0026 Ford Remix)_tabata.mp3", 
    "Tream - Lebenslang (HBz Remix)  Videoclip_tabata.mp3", 
    "Tream x HBz - Goldmarie (Official Lyric Live Video)_tabata.mp3", 
    "Udo Jürgens - Griechischer Wein (HBz Hard-Bounce Remix)_tabata.mp3", 
    "Unendlichkeit (Norda, Master Blaster, Emjo Extended)_tabata.mp3", 
    "W&W x AXMO ft. SONJA - Rave Love (Official Video)_tabata.mp3", 
    "W&W x AXMO ft. SONJA - StarShine (I Don't Want This Night To End) [Official Music Video]_tabata.mp3", 
    "We Are Young_tabata.mp3", 
    "Without You_tabata.mp3", 
    "Wu0026W x HARRIS u0026 FORD x SPECIAL D. - COME WITH ME (Official Video)_tabata.mp3"
];
